ARG RUBY_VERSION=3.4
ARG RUBY_OS=slim-trixie
FROM ruby:${RUBY_VERSION}-${RUBY_OS}

RUN apt-get update \
    && apt-get install -y \
        # for healthchecks
        netcat-openbsd \
        curl \
        # for building native extensions
        build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

# copy node binary from node image to avoid installing nodejs via apt-get
COPY --from=node:24-trixie-slim /usr/local/bin/node /usr/local/bin/node

RUN apt-get update \
    && apt-get install -y \
        # for nokogiri
        libyaml-dev \
        # for sqlite3
        pkg-config \
        libsqlite3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

WORKDIR /app

# Copy the Gemfile and Gemfile.lock first to leverage Docker cache
COPY cookbook/Gemfile cookbook/Gemfile.lock ./

# Update RubyGems and install Bundler
RUN gem update --system \
    && gem install bundler:2.4.14

# Copy the rest of the application code
COPY ./cookbook/ .

# Install the gems specified in the Gemfile
RUN bundle install

COPY "BuildTools/ruby/entrypoint.sh" /
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3003

CMD [ "rails", "server", "-b", "0.0.0.0", "--port", "3003" ]
